//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_ConsoleApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Client_ConsoleApp1.ServiceReference1.HelloWorldResponse HelloWorld(Client_ConsoleApp1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_ConsoleApp1.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Client_ConsoleApp1.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 AddResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        Client_ConsoleApp1.ServiceReference1.AddResponse Add(Client_ConsoleApp1.ServiceReference1.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_ConsoleApp1.ServiceReference1.AddResponse> AddAsync(Client_ConsoleApp1.ServiceReference1.AddRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        Client_ConsoleApp1.ServiceReference1.SayHelloResponse SayHello(Client_ConsoleApp1.ServiceReference1.SayHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHello", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_ConsoleApp1.ServiceReference1.SayHelloResponse> SayHelloAsync(Client_ConsoleApp1.ServiceReference1.SayHelloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Client_ConsoleApp1.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Client_ConsoleApp1.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_ConsoleApp1.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Client_ConsoleApp1.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public Client_ConsoleApp1.ServiceReference1.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(Client_ConsoleApp1.ServiceReference1.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num2;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(int num1, int num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_ConsoleApp1.ServiceReference1.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(Client_ConsoleApp1.ServiceReference1.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(string AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHello", Namespace="http://tempuri.org/", Order=0)]
        public Client_ConsoleApp1.ServiceReference1.SayHelloRequestBody Body;
        
        public SayHelloRequest() {
        }
        
        public SayHelloRequest(Client_ConsoleApp1.ServiceReference1.SayHelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHelloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public SayHelloRequestBody() {
        }
        
        public SayHelloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHelloResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_ConsoleApp1.ServiceReference1.SayHelloResponseBody Body;
        
        public SayHelloResponse() {
        }
        
        public SayHelloResponse(Client_ConsoleApp1.ServiceReference1.SayHelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayHelloResult;
        
        public SayHelloResponseBody() {
        }
        
        public SayHelloResponseBody(string SayHelloResult) {
            this.SayHelloResult = SayHelloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Client_ConsoleApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Client_ConsoleApp1.ServiceReference1.WebService1Soap>, Client_ConsoleApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_ConsoleApp1.ServiceReference1.HelloWorldResponse Client_ConsoleApp1.ServiceReference1.WebService1Soap.HelloWorld(Client_ConsoleApp1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Client_ConsoleApp1.ServiceReference1.HelloWorldRequest inValue = new Client_ConsoleApp1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Client_ConsoleApp1.ServiceReference1.HelloWorldRequestBody();
            Client_ConsoleApp1.ServiceReference1.HelloWorldResponse retVal = ((Client_ConsoleApp1.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_ConsoleApp1.ServiceReference1.HelloWorldResponse> Client_ConsoleApp1.ServiceReference1.WebService1Soap.HelloWorldAsync(Client_ConsoleApp1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_ConsoleApp1.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Client_ConsoleApp1.ServiceReference1.HelloWorldRequest inValue = new Client_ConsoleApp1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Client_ConsoleApp1.ServiceReference1.HelloWorldRequestBody();
            return ((Client_ConsoleApp1.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_ConsoleApp1.ServiceReference1.AddResponse Client_ConsoleApp1.ServiceReference1.WebService1Soap.Add(Client_ConsoleApp1.ServiceReference1.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public string Add(int num1, int num2) {
            Client_ConsoleApp1.ServiceReference1.AddRequest inValue = new Client_ConsoleApp1.ServiceReference1.AddRequest();
            inValue.Body = new Client_ConsoleApp1.ServiceReference1.AddRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            Client_ConsoleApp1.ServiceReference1.AddResponse retVal = ((Client_ConsoleApp1.ServiceReference1.WebService1Soap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_ConsoleApp1.ServiceReference1.AddResponse> Client_ConsoleApp1.ServiceReference1.WebService1Soap.AddAsync(Client_ConsoleApp1.ServiceReference1.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_ConsoleApp1.ServiceReference1.AddResponse> AddAsync(int num1, int num2) {
            Client_ConsoleApp1.ServiceReference1.AddRequest inValue = new Client_ConsoleApp1.ServiceReference1.AddRequest();
            inValue.Body = new Client_ConsoleApp1.ServiceReference1.AddRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((Client_ConsoleApp1.ServiceReference1.WebService1Soap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_ConsoleApp1.ServiceReference1.SayHelloResponse Client_ConsoleApp1.ServiceReference1.WebService1Soap.SayHello(Client_ConsoleApp1.ServiceReference1.SayHelloRequest request) {
            return base.Channel.SayHello(request);
        }
        
        public string SayHello(string name) {
            Client_ConsoleApp1.ServiceReference1.SayHelloRequest inValue = new Client_ConsoleApp1.ServiceReference1.SayHelloRequest();
            inValue.Body = new Client_ConsoleApp1.ServiceReference1.SayHelloRequestBody();
            inValue.Body.name = name;
            Client_ConsoleApp1.ServiceReference1.SayHelloResponse retVal = ((Client_ConsoleApp1.ServiceReference1.WebService1Soap)(this)).SayHello(inValue);
            return retVal.Body.SayHelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_ConsoleApp1.ServiceReference1.SayHelloResponse> Client_ConsoleApp1.ServiceReference1.WebService1Soap.SayHelloAsync(Client_ConsoleApp1.ServiceReference1.SayHelloRequest request) {
            return base.Channel.SayHelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_ConsoleApp1.ServiceReference1.SayHelloResponse> SayHelloAsync(string name) {
            Client_ConsoleApp1.ServiceReference1.SayHelloRequest inValue = new Client_ConsoleApp1.ServiceReference1.SayHelloRequest();
            inValue.Body = new Client_ConsoleApp1.ServiceReference1.SayHelloRequestBody();
            inValue.Body.name = name;
            return ((Client_ConsoleApp1.ServiceReference1.WebService1Soap)(this)).SayHelloAsync(inValue);
        }
    }
}
